[package]
name = "salt_atproto_core"
version = "0.1.0"
edition.workspace = true

[dependencies]
atrium-api.workspace = true
atrium-xrpc-client.workspace = true
hickory-client = "0.25.2"
ipld-core.workspace = true
thiserror.workspace = true
tokio.workspace = true
